In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [11]:
df=pd.read_csv("Pre-Owned Car Resale in India-2021.csv")
df=df.rename(columns={'distance_covered (km)':'distance_covered'})
df

,model_year,maker,model_name,city,distance_covered,fuel_type,pre_owner,price (₹)
0,2012,Maruti,Alto K10 VXI,Mumbai,29067,Petrol,2nd Owner,165199
1,2011,Hyundai,i20 SPORTZ 1.2 O,Mumbai,36791,Petrol,2nd Owner,326099
2,2010,Maruti,A Star VXI,Mumbai,35171,Petrol,1st Owner,195199
3,2011,Hyundai,Santro Xing GLS,Mumbai,19908,Petrol,1st Owner,195199
4,2012,Hyundai,Santro Xing GLS,Mumbai,43847,Petrol,3rd Owner,203299
...,...,...,...,...,...,...,...,...
3360,2014,Honda,City S MT DIESEL,Kolkata,61643,Diesel,3rd Owner,500000
3361,2006,Maruti,Wagon R LXI,Kolkata,26500,Petrol,1st Owner,100000
3362,2016,Maruti,S Cross ZETA 1.3,Kolkata,57828,Diesel,1st Owner,550000
3363,2012,BMW,3 Series 320D,Kolkata,23782,Diesel,2nd Owner,1200000
3364,2016,Hyundai,Creta 1.4 BASE,Kolkata,33130,Diesel,1st Owner,850000

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score

In [13]:
x=df[['model_year','maker','distance_covered','fuel_type','pre_owner']]
y=df['price (₹)']

In [14]:
df

,model_year,maker,model_name,city,distance_covered,fuel_type,pre_owner,price (₹)
0,2012,Maruti,Alto K10 VXI,Mumbai,29067,Petrol,2nd Owner,165199
1,2011,Hyundai,i20 SPORTZ 1.2 O,Mumbai,36791,Petrol,2nd Owner,326099
2,2010,Maruti,A Star VXI,Mumbai,35171,Petrol,1st Owner,195199
3,2011,Hyundai,Santro Xing GLS,Mumbai,19908,Petrol,1st Owner,195199
4,2012,Hyundai,Santro Xing GLS,Mumbai,43847,Petrol,3rd Owner,203299
...,...,...,...,...,...,...,...,...
3360,2014,Honda,City S MT DIESEL,Kolkata,61643,Diesel,3rd Owner,500000
3361,2006,Maruti,Wagon R LXI,Kolkata,26500,Petrol,1st Owner,100000
3362,2016,Maruti,S Cross ZETA 1.3,Kolkata,57828,Diesel,1st Owner,550000
3363,2012,BMW,3 Series 320D,Kolkata,23782,Diesel,2nd Owner,1200000
3364,2016,Hyundai,Creta 1.4 BASE,Kolkata,33130,Diesel,1st Owner,850000

In [15]:
x=pd.get_dummies(x,columns=['maker','fuel_type','pre_owner'])

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
x_train.columns

Index(['model_year', 'distance_covered', 'maker_Audi', 'maker_BMW',
       'maker_Chevrolet', 'maker_Datsun', 'maker_Fiat', 'maker_Ford',
       'maker_Honda', 'maker_Hyundai', 'maker_Jeep', 'maker_KIA', 'maker_MG',
       'maker_Mahindra', 'maker_Maruti', 'maker_Mercedes', 'maker_Nissan',
       'maker_Renault', 'maker_Skoda', 'maker_Ssangyong', 'maker_Tata',
       'maker_Toyota', 'maker_Volkswagen', 'maker_Volvo', 'fuel_type_Diesel',
       'fuel_type_Electric', 'fuel_type_Petrol', 'fuel_type_Petrol + CNG',
       'fuel_type_Petrol + LPG', 'pre_owner_1st Owner', 'pre_owner_2nd Owner',
       'pre_owner_3rd Owner', 'pre_owner_4th Owner', 'pre_owner_6th Owner'],
      dtype='object')

In [17]:
model=LinearRegression()
model.fit(x_train, y_train)

y_pred=model.predict(x_test)
print(y_pred)

[ 466438.04045217  449328.82582186  765262.99447     653235.11658697
  446770.46219641  474543.37602982  487168.17040639  485167.60750642
  205109.71358185  227787.34948428  316994.79289047  530126.16997035
  408685.00803088  445321.50728735  335172.92373396  530862.12348863
  811406.31568326  276765.83669728  423138.09872817  399229.6241708
  212558.87027606  265112.44355047  589972.07027628  599827.8073303
  557397.59069121  526769.08856477  576107.3063505   595648.36853585
  512387.05374119 1572069.13777499  254476.34937868  429113.75960298
  447845.7273407   356139.7394222   683487.69004539  207769.47473589
  666076.213       488163.65248708  579318.19608796  212723.90655296
  250216.38561404  601097.16885236  190350.29031475  270906.05636913
  121747.18533795  445456.05291931  766754.72101353  388873.33838892
  331926.6145238   572549.32369272  352332.29211605  601515.38622622
  247389.9183481   297116.95881212  481178.24790215  745136.34649876
  191511.84089392  273012.61824234  370787.0442542   513647.6422226
  531651.18108396  388009.34733889  558496.18180235  715663.78062229
  844533.77656487  574313.78720936  408379.1915223   556423.67996922
  378091.90907019  581036.8262734   559051.77330472  131378.24884254
  314128.58891112  530031.93719278  397923.26681513  141677.93647258
  277261.81328939  528257.51231654  271788.83068082  444144.88772075
  493585.91475199  300333.78726415  591952.57965814  186399.47267598
  577720.47193769  310660.14149567  101615.86601387  557410.59543379
  141779.49731937  324689.24891992  394473.91366458  290872.93888415
  468237.85999848  528696.13837294  335212.04117395  351301.64548481
  427530.48380019  490977.32853036  175384.7437371   275944.15557133
  572810.86351569  487485.85768938  276151.41285008  536472.01851532
  544539.920197    448886.9433867   598060.14997785  308687.54911347
  581163.94062389  615723.44969288  528479.38781409  290176.35318969
  613998.68231583  708518.80144821  480253.77584441  566490.58561751
  532724.85627863  480820.92711797  203468.27622624  237109.69998907
  447897.58165254  481164.62388611  268547.86304826  643954.12499723
  188568.42569511  398752.44799784   21245.7963164   615269.83188628
  373878.88853602  209560.01906195  211679.1544888   579173.12280723
  297523.31789584  378430.96128742  393178.72716758  508220.3748187
  421147.65062799  721808.33759423  199951.42090246  421549.14625204
  485805.04631725  600251.24131131  361056.86227639  205954.50578822
  375001.75458573  386311.30088875  470597.68191691  444810.76288261
  126505.39244089  252916.10824595 1364624.98837417  619257.96140556
  308265.94260979  562559.80123705  555185.75233045  251512.73138216
  599132.98825625  387993.42337085  533121.02663204  533696.12524828
  484974.39418812  524649.36575244  710994.83232601  189120.61119348
  468004.02682613  232392.75799996  670637.30450267  307490.18388608
  401905.09192568  142049.81018297  172408.82514375  810574.33637942
  484493.42513721  333538.14502208  436238.49431929  486936.25249708
  230075.43672718   43380.14914291  226293.35813044  366360.93806148
  571562.4584561   550833.11764906  245080.48999132  142401.04144482
  399873.04929169  313627.39026062  428417.47624348  528337.08895564
  272282.49483758  221677.19057633  476682.24333498  201910.08099842
  451955.43241994  573371.20278123  360777.50850144  166742.38814804
  101712.98873425  387366.92106256  491405.49604553  330650.65334567
  602109.73254754  299955.40981598  287072.32111801  314237.89067611
  624036.96742249  299736.91086471  464195.75447983  454465.97795282
  304262.87091871  251138.25902575  340622.71823227  508323.54326242
  603812.93960984  677690.69825575  580448.61970234  441089.70212501
  340552.80889964  638307.86461678  484787.50106952  559092.43892834
  179773.40085916  380966.98930244  384710.06615572  571610.03929998
  248589.34782034  569334.88160653  266269.34957874  525367.87915808
   98549.32707146  563080.76275592  533203.66881423  490719.54748064
  184067.3397916   141186.33656067  491141.95205745  532168.74871503
  517031.86981452  558448.23833743  302795.39788571  383349.52237265
  444330.15369637  404237.11956485  190002.97265619  291099.48537964
  437740.93068314  634450.49376445  276263.1930754   399424.64232516
  388417.96460767  270380.18999265  446776.07742353  485793.46057104
  216033.82006279  400145.32318789  593495.1169681   397460.87596789
  543800.58456935  590771.81171691  381531.40407339  147046.52127585
  242304.8830345   396973.9206069   648573.85199553  295445.62080623
  233597.59379497  379431.29434353  576137.96038659  553232.73563001
  204718.95203105  224490.6530997   306256.5118857   121579.46544358
  423642.06576926  357430.09822245  192583.28718525  600271.36906514
  403213.66696638  426497.63888763  581067.17067274  243053.60933597
  572481.82288601  648550.52466218  187310.5780935   527171.35690245
  385879.77050208  462207.98989795  232675.17752016  645273.38251674
  181550.81889044  612965.64556324  663625.67554614  343485.92905661
  401200.77158159  506328.88180025  185017.30527328  253171.12599117
  338852.42184573 -111555.24128808  315643.22857252  640146.31572784
  430695.79549235  409913.38852553  386501.62289774  461978.96193144
  477373.86857322  660832.3394101   250778.16985098  407272.34343174
  380738.6048623   258211.29080473  313327.97154459  472768.64822955
  462825.79240762  530977.77418475  227756.80451947  408578.64780311
  313886.96905099  603538.65216534  335160.15087488  554248.42254135
  228596.39034416  341747.52525306  552661.69693559  595771.83134526
  379637.69474524  579815.82544243  428312.72938749  446110.20501801
  465145.39198481  531803.72877866 1879925.14371996  614474.37513191
  287974.84368829  489794.51622918  492390.09907474 -218844.49234577
  235205.12447479  449532.56678893  474235.49925609   18410.58227651
  360490.32181434  363118.93967299  339580.83444133  665761.54969627
  275214.65144002  548131.67990914  710591.06603263  604446.30062751
  251081.45764792  554309.42097679  400054.13379329  293347.497568
  145910.98018183  687024.72911797  530438.07736775  149930.27979842
  105659.14564021  736359.33447522  620728.26156864  450422.66916984
  399603.25248931  322161.70943348  469194.14242759  355337.76023501
  475256.68118522  295413.86607984  663571.97435573  383869.91713375
  255486.79723457  121038.73650415  435955.71874936  142590.33269791
  467313.67477915  484016.17172703  316533.02131671 1381982.53751931
  364836.53636952  295162.04654765  201879.58323477  556373.93166825
  393403.58739144  279247.57370615  728734.22041011  232556.68986554
  303295.56578025  470794.55789164  201631.61436765  373378.20594676
  468230.75935437  482605.67321849  580483.71186484  365823.65825856
  189090.06575817  403662.53700982  252049.53825636  448595.50283758
  382837.28001219  405597.97298466  475700.23488858  371744.66578178
  238323.88881202  487942.31245446  335266.95008706  425273.16658409
  266829.2759953   346189.43989235  467863.32377042  212105.83253357
  463982.2083497   316926.47484775  444062.05404864  302293.27169155
  362797.85732779  532591.1571382   358925.21136627  515646.96657567
  205830.21990807  429695.97986396  356877.97055757  105161.83428551
  259521.87986235  378568.93008086  443851.40508685  535358.62628746
  590162.34342386  540148.99913526  275481.66151185 1386125.62452196
  710039.11778297  142689.06104462  304548.35598198  347675.513699
  716208.01877797  398295.01133826    9691.12958713  557787.62975632
  426676.40249196  462581.18566103  185843.106427    723039.74827725
  547202.8988885   551694.51334932  666270.54934467  272942.12428059
  449351.22287852   61501.67337263  462060.99595791  141635.00017962
  428319.64460775  281136.27403796  321132.37373717  311758.52890055
  305802.3833641   490076.90228812  515197.06577629  274802.11210601
  365803.69652973  622396.37783492  117972.40398622  376772.44375971
 1179618.01583153  485593.66764423  228399.10140114 1111390.79265076
  770943.8849352   236931.65887044 1030566.33444284  719724.98389117
  681310.18082573  279002.755633    398605.91258824  486339.68573436
  527442.23881157  381885.45671014  189386.27950615  206515.8771762
  187085.57540445  322831.96973747  314136.12340483  418356.79158577
  362677.93921903  236917.93164216  139606.2603374   173357.07386014
   83184.16949201  684869.62284635  152179.37777877  359116.7732887
  556323.87373054  129833.26478179  447972.30731624  365114.45611486
  503187.30448399  623050.43381681  661924.91338696  609114.01826018
  372567.7834172   704149.0015174   430377.59351465  142728.01782966
  210367.12045979  430727.48165086  442509.64593193  402648.27030095
  169718.18686637  465981.35242255  349129.30658878  318957.37368514
  380852.78357773  232189.77034281  443817.55147123  284522.84929584
  343012.59771165  528134.07047428 1163137.47211476  516525.09633642
  401049.97849503  399541.47858387  402114.84345575  295483.53297715
  275204.94948922  400293.79262081   74782.79614967  488543.67996466
  447689.37173483  472681.33067223  390416.2514921   503898.40359432
  192248.56988221  426658.64998622  280516.02841058  529519.12578681
  396367.13583216  405780.142593    270336.63442624  442413.01329777
  399074.1865333   218676.36311226  252392.09968984  732716.04552068
  429290.3557502  1181117.26136108  256635.03343445  715155.56353931
  362964.11994246  589791.97736138  514398.20301791  404439.99306796
  350133.82289527  471350.6138608   490990.9956789   549883.398092
  550384.98255843  471707.5231625   336456.67760849  202303.81101121
  458469.8248087   208227.54900889  578267.49682391  600484.39913404
  199876.79981752  218176.15874137  486955.03712524  576193.59178539
  927003.51890954  464434.43141285  205609.67368542  359337.64748804
  333966.6822537   514501.93132181  258438.02591468  105369.38564362
   83644.94097926  420777.73795021  623528.51292492  615433.0606699
  271450.50094929  917843.79099707  551227.56282347  493633.03112912
  608971.69529022  158816.35733531  292945.64850827  537221.92784645
   44084.88233596  416632.68122377  314246.87014122  487317.6217338
  123346.04618938  481302.31173608  429875.72260642  207221.44145572
  370833.59699462  393104.39041638  255758.76012753  117950.83262749
  301155.56314042  344734.17655315  744011.8491147   273636.89814702
  187240.49698071  166238.73180747  360958.69386324  385878.01589395
  556499.60953549  443244.36090332  529720.80250902  710095.88451643
  470218.98262815  350029.24495697  486731.58261983  245466.84375873
  378716.73764747 1732794.6422229   553960.57002547  603233.97191268
  401345.88799481  444282.62583677  301559.22622156  311319.97736315
  257909.9110561   485912.28383739  514922.624423    179955.98331647
  442033.94070539  339084.61474743  599972.53497821 1076203.49063721
  362082.39491069  387108.61546348  356144.95721002  424370.32998714
  532373.35714604  405857.13892604  572985.49863032  746583.58856569
  472425.57073486  316626.42839633  372913.95727916  316767.82916881
  274057.02292606  557921.90888405  482334.4314447  1817541.20410034
  645264.14500932  458347.07655151  656783.32312955  299441.24553311
  605082.34834912  399143.44194815  172630.76930837  529571.92022714
  315678.83679624  445880.45456579  384303.92598075  720617.97621489
  374305.41167486  357068.62874921  340637.16794625  242442.69607152
  484820.99482046  899125.55048759  488457.7041665   417952.66267137
  667333.36894011  527076.35141124  484680.85856992  290728.54495664
  422418.79426895  571579.33503596  313986.98171414  719317.24530463
  529590.08558184]

In [18]:
import joblib

joblib.dump(model,'Assignment1.pkl')

['Assignment1.pkl']